
repos:

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.6
    hooks:
      - id: uv-sync
      - id: uv-lock
      - id: uv-export
        args: [ --format, requirements.txt, --output-file, requirements.txt ]
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyproject]
        args: [ --fix ] # If you live dangerously, add the --fix-unsafe flag.
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyproject]

  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
    - id: pytest
      additional_dependencies:
        - pytest-custom_exit_code
      args:
        - "--suppress-no-test-exit-code" # Remove argument if hook should fail on the absence of tests.
      fail_fast: true
      stages: [pre-commit]
      
  - repo: local
    hooks:
      - id: write-documentation
        name: Sync project documentation.
        entry: python .python/scripts/write_documentation.py
        fail_fast: true
        language: python
        additional_dependencies:
          - jinja2
        files: pyproject.toml
        stages: [pre-commit]
