[project]
name = "defleopard"
version = "0.2.0b1"
description = "Tools for Hybrid Programming."
readme = "README.md"
authors = [
    { name = "IAmSorryDave", email = "212933284+IAmSorryDave@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []
license = "MIT"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"
