name: Add ➕ Feature 🔧

on:
  pull_request:
    branches:
      - features
    types: closed

permissions:
  contents: write

jobs:

  increment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install UV
      uses: astral-sh/setup-uv@v7
    
    - name: Dry Run Version Increment
      run: |
        uv version --bump alpha --dry-run

    - name: Version Increment Alpha Alone
      run: |
        uv version --bump alpha
    
    - name: Verify Version Changed
      run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

    - name: Increment Alpha Version
      id: version
      shell: bash
      run: |
        VERSION=$(uv version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Commit & Push Version Change
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        branch: features
        commit_message: "chore: bump features version to ${{ steps.version.outputs.version }}"
        file_pattern: pyproject.toml
  
