
name: PyPI Production Release 🐍

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  id-token: write

jobs:

  build:
    if: github.event.pull_request.merged == true
    name: Build Distribution 📦; Cache Distribution ⬆️
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    
      - name: Checkout Project
        uses: actions/checkout@v7

      - name: Install UV
        uses: astral-sh/setup-uv@v7
      
      - name: Dry Run Stable Version Increment
        run: |
          uv version --bump stable --dry-run

      - name: Stable Version Increment
        run: |
          uv version --bump stable 

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Dry Run Major Version Increment
        run: |
          uv version --bump major --dry-run

      - name: Major Version Increment
        run: |
          uv version --bump major

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Build Distribution
        run: uv build

      - name: Store Distribution Packages
        uses: actions/upload-artifact@v7
        with:
          name: pypi-python-package-distributions
          path: dist/
          if-no-files-found: error
          overwrite: 'true'
          retention-days: 1

  publish-to-pypi:
    name: Publish Python 🐍 Distribution 📦 to PyPi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ steps.repo_name.outputs.name }}
    
    permissions: write-all
    
    steps:
    - name: Set Lowercase Repository Name
      id: repo_name
      run: echo "name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    
    - name: Download Distribution Packages
      uses: actions/download-artifact@v8
      with:
        name: pypi-python-package-distributions
        path: dist/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        workflow: prepare-pypi-release
        run_conclusion: success
    
    - name: Publish Distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true

  finalize:
    name: Increment Version ⬆️ and Issue Release
    runs-on: ubuntu-latest
    needs: publish-to-pypi
    
    steps:

      - name: Checkout Project
        uses: actions/checkout@v7

      - name: Install UV
        uses: astral-sh/setup-uv@v7
      
      - name: Dry Run Stable Version Increment
        run: |
          uv version --bump stable --dry-run

      - name: Stable Version Increment
        run: |
          uv version --bump stable

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Dry Run Major Version Increment
        run: |
          uv version --bump major --dry-run

      - name: Major Version Increment
        run: |
          uv version --bump major

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Extract Version
        id: version
        shell: bash
        run: |
          VERSION=$( uv version )
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Tag release
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: "Released v$(uv version)"
          tag_name: "v$(uv version)"
